# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cs_gamesystem.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cs_gamesystem.proto',
  package='SProtoSpace',
  serialized_pb='\n\x13\x63s_gamesystem.proto\x12\x0bSProtoSpace*\xc8\x02\n\x0b\x45GameSystem\x12\x14\n\x10GAME_SYSTEM_BASE\x10\x01\x12\x14\n\x10GAME_SYSTEM_ITEM\x10\x02\x12\x16\n\x12GAME_SYSTEM_PLAYER\x10\x03\x12\x14\n\x10GAME_SYSTEM_HERO\x10\x04\x12\x14\n\x10GAME_SYSTEM_SOUL\x10\x05\x12\x15\n\x11GAME_SYSTEM_QUEST\x10\x06\x12\x15\n\x11GAME_SYSTEM_LEVEL\x10\x07\x12\x15\n\x11GAME_SYSTEM_ROYAL\x10\x08\x12\x14\n\x10GAME_SYSTEM_SHOW\x10\t\x12\x16\n\x12GAME_SYSTEM_FRIEND\x10\n\x12\x14\n\x10GAME_SYSTEM_SHOP\x10\x0b\x12\x15\n\x11GAME_SYSTEM_TOWER\x10\x0c\x12\x14\n\x10GAME_SYSTEM_CHAT\x10\r\x12\x13\n\x0fGAME_SYSTEM_MAX\x10?*\x8a\x01\n\x14\x45SystemConditionType\x12\x19\n\x15SYSTEM_CONDITION_NONE\x10\x00\x12\x1a\n\x16SYSTEM_CONDITION_LEVEL\x10\x01\x12\x1c\n\x18SYSTEM_CONDITION_TASK_ID\x10\x02\x12\x1d\n\x19SYSTEM_CONDITION_STAGE_ID\x10\x03*f\n\x0f\x45TowerFloorType\x12\x1a\n\x16\x45Tower_Floor_TP_Battle\x10\x01\x12\x1c\n\x18\x45Tower_Floor_TP_Question\x10\x02\x12\x19\n\x15\x45Tower_Floor_TP_Raids\x10\x03')

_EGAMESYSTEM = _descriptor.EnumDescriptor(
  name='EGameSystem',
  full_name='SProtoSpace.EGameSystem',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GAME_SYSTEM_BASE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_SYSTEM_ITEM', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_SYSTEM_PLAYER', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_SYSTEM_HERO', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_SYSTEM_SOUL', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_SYSTEM_QUEST', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_SYSTEM_LEVEL', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_SYSTEM_ROYAL', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_SYSTEM_SHOW', index=8, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_SYSTEM_FRIEND', index=9, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_SYSTEM_SHOP', index=10, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_SYSTEM_TOWER', index=11, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_SYSTEM_CHAT', index=12, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_SYSTEM_MAX', index=13, number=63,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=37,
  serialized_end=365,
)

EGameSystem = enum_type_wrapper.EnumTypeWrapper(_EGAMESYSTEM)
_ESYSTEMCONDITIONTYPE = _descriptor.EnumDescriptor(
  name='ESystemConditionType',
  full_name='SProtoSpace.ESystemConditionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SYSTEM_CONDITION_NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYSTEM_CONDITION_LEVEL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYSTEM_CONDITION_TASK_ID', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYSTEM_CONDITION_STAGE_ID', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=368,
  serialized_end=506,
)

ESystemConditionType = enum_type_wrapper.EnumTypeWrapper(_ESYSTEMCONDITIONTYPE)
_ETOWERFLOORTYPE = _descriptor.EnumDescriptor(
  name='ETowerFloorType',
  full_name='SProtoSpace.ETowerFloorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ETower_Floor_TP_Battle', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ETower_Floor_TP_Question', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ETower_Floor_TP_Raids', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=508,
  serialized_end=610,
)

ETowerFloorType = enum_type_wrapper.EnumTypeWrapper(_ETOWERFLOORTYPE)
GAME_SYSTEM_BASE = 1
GAME_SYSTEM_ITEM = 2
GAME_SYSTEM_PLAYER = 3
GAME_SYSTEM_HERO = 4
GAME_SYSTEM_SOUL = 5
GAME_SYSTEM_QUEST = 6
GAME_SYSTEM_LEVEL = 7
GAME_SYSTEM_ROYAL = 8
GAME_SYSTEM_SHOW = 9
GAME_SYSTEM_FRIEND = 10
GAME_SYSTEM_SHOP = 11
GAME_SYSTEM_TOWER = 12
GAME_SYSTEM_CHAT = 13
GAME_SYSTEM_MAX = 63
SYSTEM_CONDITION_NONE = 0
SYSTEM_CONDITION_LEVEL = 1
SYSTEM_CONDITION_TASK_ID = 2
SYSTEM_CONDITION_STAGE_ID = 3
ETower_Floor_TP_Battle = 1
ETower_Floor_TP_Question = 2
ETower_Floor_TP_Raids = 3




# @@protoc_insertion_point(module_scope)
