# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ss_charge.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import ss_protoid_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ss_charge.proto',
  package='SProtoSpace',
  serialized_pb='\n\x0fss_charge.proto\x12\x0bSProtoSpace\x1a\x10ss_protoid.proto')





# @@protoc_insertion_point(module_scope)
